/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Review = {
  _id: string;
  _type: 'review';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  username?: string;
  role?: string;
  rating?: number;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  reviewedAt?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  featuredBrand?: Array<{
    name?: string;
    image?: ImageWithAlt;
    _key: string;
  }>;
  memberAccessFeatures?: Array<{
    title?: string;
    body?: string;
    image?: ImageWithAlt;
    _key: string;
  }>;
  navigation?: Array<
    | {
        label?: string;
        href?: string;
        isButton?: boolean;
        _type: 'navLink';
        _key: string;
      }
    | {
        label?: string;
        dropdownItems?: Array<{
          label?: string;
          href?: string;
          isButton?: boolean;
          _type: 'dropdownItem';
          _key: string;
        }>;
        _type: 'navDropdown';
        _key: string;
      }
  >;
  footerDescription?: string;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  contactInfo?: {
    address1?: string;
    address2?: string;
    zip?: string;
    city?: string;
    state?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    email?: string;
    phone?: string;
  };
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  author?: AuthorReference;
  category?: CategoryReference;
  minRead?: number;
  publishedAt?: string;
  image?: ImageWithAlt;
  seo?: Seo;
  body?: BlockContent;
  excerpt?: string;
  isFeatured?: boolean;
  isMemberOnly?: boolean;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  image?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Membership = {
  _id: string;
  _type: 'membership';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  pricePerMonth?: number;
  desc?: string;
  features?: Array<string>;
  isFeatured?: boolean;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
};

export type OurStory = {
  _id: string;
  _type: 'ourStory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  year?: number;
  body?: string;
};

export type Member = {
  _id: string;
  _type: 'member';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  role?: string;
  email?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?:
    | 'twitter'
    | 'facebook'
    | 'youtube'
    | 'instagram'
    | 'linkedin'
    | 'github';
  url?: string;
};

export type Faq = {
  _type: 'faq';
  title?: string;
  body?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Review
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSetting
  | ImageWithAlt
  | UtilityPage
  | Seo
  | BlockContent
  | Slug
  | AuthorReference
  | CategoryReference
  | Blog
  | Category
  | Author
  | Membership
  | Faqs
  | OurStory
  | Member
  | SocialLink
  | Faq
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: HERO_BLOG_QUERY
// Query: *[_type == 'blog' && defined(slug.current)]|order(isFeatured desc){  name,  "imageUrl": image.asset->url,  "imageAlt": image.alt,  "slug": slug.current,  "author": author->name,  "category": category->name,  excerpt, }
export type HERO_BLOG_QUERY_RESULT = Array<{
  name: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  slug: string | null;
  author: string | null;
  category: string | null;
  excerpt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_BRANDS_QUERY
// Query: *[_type == 'siteSetting'][0]{  featuredBrand[]{    name,    "imageUrl": image.asset->url,    "imageAlt": image.alt,    _key  }}
export type FEATURED_BRANDS_QUERY_RESULT = {
  featuredBrand: Array<{
    name: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: OUR_STORY_QUERY
// Query: *[_type == 'ourStory' && defined(slug.current)]  |order(year){  year,  "slug": slug.current,  body,  name }
export type OUR_STORY_QUERY_RESULT = Array<{
  year: number | null;
  slug: string | null;
  body: string | null;
  name: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBER_ACCESS_FEATURES_QUERY
// Query: *[_type == 'siteSetting'][0]{  memberAccessFeatures[]{    title,    body,    "image": {      "imageUrl": image.asset->url,      "imageAlt": image.alt    }  }}
export type MEMBER_ACCESS_FEATURES_QUERY_RESULT = {
  memberAccessFeatures: Array<{
    title: string | null;
    body: string | null;
    image: {
      imageUrl: string | null;
      imageAlt: string | null;
    };
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERS_QUERY
// Query: *[_type == 'member' && defined(slug.current)]| order(_createdAt desc){  name,  "imageUrl": image.asset->url,  "imageAlt": image.alt,  email,  role}
export type MEMBERS_QUERY_RESULT = Array<{
  name: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  email: string | null;
  role: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERSHIPS_QUERY
// Query: *[_type == 'membership' && defined(slug.current)]  | order(isFeatured desc){    name,    "slug": slug.current,    pricePerMonth,    desc,    features[],    "imageUrl": image.asset->url,    "imageAlt": image.alt,    isFeatured  }
export type MEMBERSHIPS_QUERY_RESULT = Array<{
  name: string | null;
  slug: string | null;
  pricePerMonth: number | null;
  desc: string | null;
  features: Array<string> | null;
  imageUrl: string | null;
  imageAlt: string | null;
  isFeatured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FAQs_QUERY
// Query: *[_type == 'faqs' && defined(slug.current)]|order(_createdAt desc){  name,  "slug": slug.current,  faqs[]{    title,    body  } }
export type FAQsQUERYResult = Array<{
  name: string | null;
  slug: string | null;
  faqs: Array<{
    title: string | null;
    body: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_type == 'siteSetting'][0]{  footerDescription,  footerColumns[]{    title,    links[]{      label,      href    }  },  contactInfo,  "logoUrl": secondaryLogo.asset->url,  "logoAlt": secondaryLogo.alt,  socialLinks[]{    platform,    url  }}
export type FOOTER_QUERY_RESULT = {
  footerDescription: string | null;
  footerColumns: Array<{
    title: string | null;
    links: Array<{
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
  contactInfo: {
    address1?: string;
    address2?: string;
    zip?: string;
    city?: string;
    state?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    email?: string;
    phone?: string;
  } | null;
  logoUrl: string | null;
  logoAlt: string | null;
  socialLinks: Array<{
    platform:
      | 'facebook'
      | 'github'
      | 'instagram'
      | 'linkedin'
      | 'twitter'
      | 'youtube'
      | null;
    url: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HEADER_QUERY
// Query: *[_type == 'siteSetting'][0]{  navigation[]{    _type,    label,    "isButton": select(_type == 'navLink' => isButton == true),    "href": select(_type == 'navLink' => href),    "dropdownItems": select(_type == 'navDropdown' => dropdownItems[]{      label,      href,      "isButton": isButton == true    })  },  "logoUrl": primaryLogo.asset->url,  "logoAlt": primaryLogo.alt,  socialLinks[]}
export type HEADER_QUERY_RESULT = {
  navigation: Array<
    | {
        _type: 'navDropdown';
        label: string | null;
        isButton: null;
        href: null;
        dropdownItems: Array<{
          label: string | null;
          href: string | null;
          isButton: boolean | false;
        }> | null;
      }
    | {
        _type: 'navLink';
        label: string | null;
        isButton: boolean | false;
        href: string | null;
        dropdownItems: null;
      }
  > | null;
  logoUrl: string | null;
  logoAlt: string | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHORS_QUERY
// Query: *[_type == 'author' && defined(slug.current)] | order(name desc) {  name,  "slug": slug.current,  "imageUrl": image.asset->url,  "imageAlt": image.alt,  }
export type AUTHORS_QUERY_RESULT = Array<{
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_QUERY
// Query: *[_type == 'author' && slug.current == $slug][0] {  name,  "slug": slug.current,  "imageUrl": image.asset->url,  "imageAlt": image.alt,    body,   socialLinks[],   "blogs": *[_type == 'blog'               && defined(slug.current)              && references(^._id)]              |order(publishedAt desc){                name,                "slug": slug.current,                "imageUrl": image.asset->url,                "imageAlt": image.alt,                "author": author->name,                "cateogry": category->name,                excerpt,              } }
export type AUTHOR_QUERY_RESULT = {
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  body: BlockContent | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  blogs: Array<{
    name: string | null;
    slug: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
    author: string | null;
    cateogry: string | null;
    excerpt: string | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BLOGS_QUERY
// Query: *[_type == 'blog'   && defined(slug.current)  && (!defined($category))   || (category->name match $category) ]|order(publishedAt desc){    name,    "slug": slug.current,    "imageUrl": image.asset->url,    "imageAlt": image.alt,    "author": author->name,    "category": category->name,    excerpt,}
export type BLOGS_QUERY_RESULT = Array<
  | {
      name: null;
      slug: null;
      imageUrl: null;
      imageAlt: null;
      author: null;
      category: null;
      excerpt: null;
    }
  | {
      name: Slug | null;
      slug: null;
      imageUrl: null;
      imageAlt: null;
      author: null;
      category: null;
      excerpt: null;
    }
  | {
      name: string | null;
      slug: string | null;
      imageUrl: null;
      imageAlt: null;
      author: null;
      category: null;
      excerpt: null;
    }
  | {
      name: null;
      slug: null;
      imageUrl: string | null;
      imageAlt: null;
      author: null;
      category: null;
      excerpt: null;
    }
  | {
      name: string | null;
      slug: string | null;
      imageUrl: string | null;
      imageAlt: string | null;
      author: null;
      category: null;
      excerpt: null;
    }
  | {
      name: string | null;
      slug: string | null;
      imageUrl: string | null;
      imageAlt: string | null;
      author: string | null;
      category: string | null;
      excerpt: string | null;
    }
>;

// Source: src/sanity/lib/queries.ts
// Variable: UTILITY_PAGE_QUERY
// Query: *[_type == 'utilityPage' && slug.current == $slug][0]{  name,  body,  "seo": {    "title": coalesce(seo.metaTitle, ""),    "description": coalesce(seo.metaDescription),    "noIndex" : seo.noIndex == true  } }
export type UTILITY_PAGE_QUERY_RESULT = {
  name: string | null;
  body: BlockContent | null;
  seo: {
    title: string | '';
    description: string | null;
    noIndex: boolean | false;
  };
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: UTILITY_PAGES_QUERY
// Query: *[_type == 'utilityPage'  && defined(slug.current)]{    "slug": slug.current  }
export type UTILITY_PAGES_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'blog\'\n && defined(slug.current)]\n|order(isFeatured desc){\n  name,\n  "imageUrl": image.asset->url,\n  "imageAlt": image.alt,\n  "slug": slug.current,\n  "author": author->name,\n  "category": category->name,\n  excerpt,\n }': HERO_BLOG_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  featuredBrand[]{\n    name,\n    "imageUrl": image.asset->url,\n    "imageAlt": image.alt,\n    _key\n  }\n}': FEATURED_BRANDS_QUERY_RESULT;
    '*[_type == \'ourStory\'\n && defined(slug.current)]\n  |order(year){\n  year,\n  "slug": slug.current,\n  body,\n  name\n }': OUR_STORY_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  memberAccessFeatures[]{\n    title,\n    body,\n    "image": {\n      "imageUrl": image.asset->url,\n      "imageAlt": image.alt\n    }\n  }\n}': MEMBER_ACCESS_FEATURES_QUERY_RESULT;
    '*[_type == \'member\'\n && defined(slug.current)]\n| order(_createdAt desc){\n  name,\n  "imageUrl": image.asset->url,\n  "imageAlt": image.alt,\n  email,\n  role\n}': MEMBERS_QUERY_RESULT;
    '*[_type == \'membership\'\n && defined(slug.current)]\n  | order(isFeatured desc){\n    name,\n    "slug": slug.current,\n    pricePerMonth,\n    desc,\n    features[],\n    "imageUrl": image.asset->url,\n    "imageAlt": image.alt,\n    isFeatured\n  }': MEMBERSHIPS_QUERY_RESULT;
    '*[_type == \'faqs\'\n && defined(slug.current)]\n|order(_createdAt desc){\n  name,\n  "slug": slug.current,\n  faqs[]{\n    title,\n    body\n  }\n }': FAQsQUERYResult;
    '*[_type == \'siteSetting\'][0]{\n  footerDescription,\n  footerColumns[]{\n    title,\n    links[]{\n      label,\n      href\n    }\n  },\n  contactInfo,\n  "logoUrl": secondaryLogo.asset->url,\n  "logoAlt": secondaryLogo.alt,\n  socialLinks[]{\n    platform,\n    url\n  }\n}': FOOTER_QUERY_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  navigation[]{\n    _type,\n    label,\n    "isButton": select(_type == \'navLink\' => isButton == true),\n    "href": select(_type == \'navLink\' => href),\n    "dropdownItems": select(_type == \'navDropdown\' => dropdownItems[]{\n      label,\n      href,\n      "isButton": isButton == true\n    })\n  },\n  "logoUrl": primaryLogo.asset->url,\n  "logoAlt": primaryLogo.alt,\n  socialLinks[]\n}': HEADER_QUERY_RESULT;
    '*[_type == \'author\'\n && defined(slug.current)]\n | order(name desc)\n {\n  name,\n  "slug": slug.current,\n  "imageUrl": image.asset->url,\n  "imageAlt": image.alt, \n }': AUTHORS_QUERY_RESULT;
    '*[_type == \'author\'\n && slug.current == $slug][0]\n {\n  name,\n  "slug": slug.current,\n  "imageUrl": image.asset->url,\n  "imageAlt": image.alt, \n   body,\n   socialLinks[],\n   "blogs": *[_type == \'blog\' \n              && defined(slug.current)\n              && references(^._id)]\n              |order(publishedAt desc){\n                name,\n                "slug": slug.current,\n                "imageUrl": image.asset->url,\n                "imageAlt": image.alt,\n                "author": author->name,\n                "cateogry": category->name,\n                excerpt,\n              }\n }': AUTHOR_QUERY_RESULT;
    '*[_type == \'blog\' \n  && defined(slug.current)\n  && (!defined($category)) \n  || (category->name match $category)\n ]|order(publishedAt desc){\n    name,\n    "slug": slug.current,\n    "imageUrl": image.asset->url,\n    "imageAlt": image.alt,\n    "author": author->name,\n    "category": category->name,\n    excerpt,\n}': BLOGS_QUERY_RESULT;
    '*[_type == \'utilityPage\'\n && slug.current == $slug][0]{\n  name,\n  body,\n  "seo": {\n    "title": coalesce(seo.metaTitle, ""),\n    "description": coalesce(seo.metaDescription),\n    "noIndex" : seo.noIndex == true\n  }\n }': UTILITY_PAGE_QUERY_RESULT;
    '*[_type == \'utilityPage\'\n  && defined(slug.current)]{\n    "slug": slug.current\n  }': UTILITY_PAGES_QUERY_RESULT;
  }
}
