/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Review = {
  _id: string;
  _type: 'review';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  username?: string;
  role?: string;
  rating?: number;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  reviewedAt?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  secondaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  navigation?: Array<
    | {
        label?: string;
        href?: string;
        isButton?: boolean;
        _type: 'navLink';
        _key: string;
      }
    | {
        label?: string;
        dropdownItems?: Array<{
          label?: string;
          href?: string;
          isButton?: boolean;
          _type: 'dropdownItem';
          _key: string;
        }>;
        _type: 'navDropdown';
        _key: string;
      }
  >;
  footerDescription?: string;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  contactInfo?: {
    address1?: string;
    address2?: string;
    zip?: string;
    city?: string;
    state?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    email?: string;
    phone?: string;
  };
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  author?: AuthorReference;
  category?: CategoryReference;
  minRead?: number;
  publishedAt?: string;
  image?: ImageWithAlt;
  seo?: Seo;
  body?: BlockContent;
  excerpt?: string;
  isFeatured?: boolean;
  isMemberOnly?: boolean;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  image?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Membership = {
  _id: string;
  _type: 'membership';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  pricePerMonth?: number;
  desc?: string;
  features?: Array<string>;
  isFeatured?: boolean;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
};

export type OurStory = {
  _id: string;
  _type: 'ourStory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  year?: number;
  body?: string;
};

export type Member = {
  _id: string;
  _type: 'member';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  role?: string;
  email?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?:
    | 'twitter'
    | 'facebook'
    | 'youtube'
    | 'instagram'
    | 'linkedin'
    | 'github';
  url?: string;
};

export type Faq = {
  _type: 'faq';
  title?: string;
  body?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Review
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSetting
  | ImageWithAlt
  | UtilityPage
  | Seo
  | BlockContent
  | Slug
  | AuthorReference
  | CategoryReference
  | Blog
  | Category
  | Author
  | Membership
  | Faqs
  | OurStory
  | Member
  | SocialLink
  | Faq
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERS_QUERY
// Query: *[_type == 'member' && defined(slug.current)]| order(_createdAt desc){  name,  "imageUrl": image.asset->url,  "imageAlt": image.alt,  email,  role}
export type MEMBERS_QUERY_RESULT = Array<{
  name: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  email: string | null;
  role: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERSHIPS_QUERY
// Query: *[_type == 'membership' && defined(slug.current)]  | order(isFeatured desc){    name,    "slug": slug.current,    pricePerMonth,    desc,    features[],    "imageUrl": image.asset->url,    "imageAlt": image.alt,    isFeatured  }
export type MEMBERSHIPS_QUERY_RESULT = Array<{
  name: string | null;
  slug: string | null;
  pricePerMonth: number | null;
  desc: string | null;
  features: Array<string> | null;
  imageUrl: string | null;
  imageAlt: string | null;
  isFeatured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FAQs_QUERY
// Query: *[_type == 'faqs' && defined(slug.current)]|order(_createdAt desc){  name,  "slug": slug.current,  faqs[]{    title,    body  } }
export type FAQsQUERYResult = Array<{
  name: string | null;
  slug: string | null;
  faqs: Array<{
    title: string | null;
    body: string | null;
  }> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'member\'\n && defined(slug.current)]\n| order(_createdAt desc){\n  name,\n  "imageUrl": image.asset->url,\n  "imageAlt": image.alt,\n  email,\n  role\n}': MEMBERS_QUERY_RESULT;
    '*[_type == \'membership\'\n && defined(slug.current)]\n  | order(isFeatured desc){\n    name,\n    "slug": slug.current,\n    pricePerMonth,\n    desc,\n    features[],\n    "imageUrl": image.asset->url,\n    "imageAlt": image.alt,\n    isFeatured\n  }': MEMBERSHIPS_QUERY_RESULT;
    '*[_type == \'faqs\'\n && defined(slug.current)]\n|order(_createdAt desc){\n  name,\n  "slug": slug.current,\n  faqs[]{\n    title,\n    body\n  }\n }': FAQsQUERYResult;
  }
}
